# Generated by Django 2.2.16 on 2022-08-30 20:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='CountIngredient',
            new_name='IngredientsCount',
        ),
    ]
